name: Calidad y Pruebas

# Se ejecuta al abrir una PR o al hacer push, excepto en la rama de despliegue
on:
  pull_request:
    branches: [ "master", "develop" ]
  push:
    branches-ignore: [ "develop" ] # Ignoramos develop porque esa la maneja Azure

jobs:
  verificacion:
    runs-on: ubuntu-latest
    
    # Definimos el directorio de trabajo por defecto para todos los 'run'
    defaults:
      run:
        working-directory: ./ISW2_C_R_1_VictorManuelSanzRubio

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # Activa el caché de pip para acelerar la ejecución

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Analizar código (Linting)
        run: flake8 .

      - name: Ejecutar Tests de Django
        env:
          # Forzamos DEBUG a True para que use SQLite en los tests
          DEBUG: 'True'
        run: |
          python manage.py test